@extends('layouts.app')
@section('title','Nominas')
@section('header','Nominas')
@section('content')
<div class="row g-3 mb-3"><div class="col-md-6"><div class="soft-card p-3"><small class="text-muted">Pendiente</small><div class="h4 fw-bold text-warning">${{ number_format($resumen['pendiente'],2) }}</div></div></div><div class="col-md-6"><div class="soft-card p-3"><small class="text-muted">Pagado</small><div class="h4 fw-bold text-success">${{ number_format($resumen['pagada'],2) }}</div></div></div></div>
<div class="soft-card p-3">
    <div class="d-flex flex-wrap justify-content-between gap-3 mb-3">
        <form class="d-flex flex-wrap gap-2" method="GET"><select name="empleado_id" class="form-select"><option value="">Empleado</option>@foreach($empleados as $empleado)<option value="{{ $empleado->id }}" @selected(request('empleado_id')==$empleado->id)>{{ $empleado->nombre_completo }}</option>@endforeach</select><input type="date" name="desde" class="form-control" value="{{ request('desde') }}"><input type="date" name="hasta" class="form-control" value="{{ request('hasta') }}"><select name="estado" class="form-select"><option value="">Estado</option>@foreach(['pendiente','pagada','cancelada'] as $estado)<option value="{{ $estado }}" @selected(request('estado')===$estado)>{{ ucfirst($estado) }}</option>@endforeach</select><button class="btn btn-outline-primary"><i class="bi bi-filter"></i></button></form>
        @if(auth()->user()->role !== 'Empleado')<a href="{{ route('nominas.create') }}" class="btn btn-primary"><i class="bi bi-plus-lg me-1"></i>Generar nomina</a>@endif
    </div>
    <div class="table-responsive"><table class="table align-middle"><thead><tr><th>Empleado</th><th>Periodo</th><th>Pago</th><th>Metodo</th><th>Total</th><th>Estado</th><th></th></tr></thead><tbody>
    @forelse($nominas as $nomina)
        <tr><td>{{ $nomina->empleado->nombre_completo }}</td><td>{{ $nomina->periodo_pago }}</td><td>{{ $nomina->fecha_pago->format('d/m/Y') }}</td><td>{{ $nomina->metodo_pago_label }}</td><td>${{ number_format($nomina->total_pagar,2) }}</td><td>@include('partials.badge',['estado'=>$nomina->estado])</td><td class="text-end"><a class="btn btn-sm btn-outline-info action-btn" href="{{ route('nominas.show',$nomina) }}"><i class="bi bi-eye"></i></a>@if(auth()->user()->role !== 'Empleado' && $nomina->estado !== 'pagada') <a class="btn btn-sm btn-outline-primary action-btn" href="{{ route('nominas.edit',$nomina) }}"><i class="bi bi-pencil"></i></a> @if($nomina->estado === 'pendiente')<form class="d-inline" method="POST" action="{{ route('nominas.pagar',$nomina) }}">@csrf @method('PATCH')<button class="btn btn-sm btn-outline-success action-btn" title="Marcar pagada"><i class="bi bi-check2"></i></button></form> <form class="d-inline" method="POST" action="{{ route('nominas.cancelar',$nomina) }}">@csrf @method('PATCH')<button class="btn btn-sm btn-outline-warning action-btn" title="Cancelar"><i class="bi bi-x-circle"></i></button></form>@endif <form class="d-inline" method="POST" action="{{ route('nominas.destroy',$nomina) }}" data-confirm="Eliminar nomina?">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger action-btn"><i class="bi bi-trash"></i></button></form>@endif</td></tr>
    @empty<tr><td colspan="7" class="text-center text-muted">Sin nominas.</td></tr>@endforelse
    </tbody></table></div>{{ $nominas->links() }}
</div>
@endsection